//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedosmotrov3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пол сотрудника.
    /// </summary>
    // *** Start programmer edit section *** (ПолСотрудника CustomAttributes)

    // *** End programmer edit section *** (ПолСотрудника CustomAttributes)
    public enum ПолСотрудника
    {
        
        // *** Start programmer edit section *** (ПолСотрудника.Мужской CustomAttributes)

        // *** End programmer edit section *** (ПолСотрудника.Мужской CustomAttributes)
        [Caption("Мужской")]
        Мужской,
        
        // *** Start programmer edit section *** (ПолСотрудника.Женский CustomAttributes)

        // *** End programmer edit section *** (ПолСотрудника.Женский CustomAttributes)
        [Caption("Женский")]
        Женский,
    }
}
